/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface MonthlyTest {
    id: string;
    marks: string;
    remark?: string;
    month: string;
    studentId: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface Attendance {
    id: string;
    status: AttendanceStatus;
    studentId: string;
    date: string;
    note?: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Fee {
    id: string;
    studentId: string;
    date: string;
    note?: string;
    createdAt: bigint;
    updatedAt: bigint;
    paymentMode: string;
    amount: string;
}
export interface Exam {
    id: string;
    marks: string;
    remark?: string;
    studentId: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
    examDate: string;
    examName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface Student {
    id: string;
    dateOfBirth: string;
    caste: string;
    name: string;
    createdAt: bigint;
    motherName: string;
    mobileNumber: string;
    updatedAt: bigint;
    penNumber: string;
    fatherName: string;
    address: string;
    aadhaarNumber: string;
    photo: ExternalBlob;
}
export enum AttendanceStatus {
    present = "present",
    absent = "absent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createStudent(name: string, fatherName: string, motherName: string, dateOfBirth: string, caste: string, mobileNumber: string, aadhaarNumber: string, penNumber: string, photo: ExternalBlob, address: string): Promise<string>;
    deleteStudent(id: string): Promise<void>;
    getAttendanceRecordsByDateRange(startDate: string, endDate: string): Promise<Array<Attendance>>;
    getAttendanceRecordsByStudent(studentId: string): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExamsByStudent(studentId: string): Promise<Array<Exam>>;
    getFeeRecordsByStudent(studentId: string): Promise<Array<Fee>>;
    getMonthlyTestsByStudent(studentId: string): Promise<Array<MonthlyTest>>;
    getStudent(id: string): Promise<Student>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordAttendance(studentId: string, date: string, status: AttendanceStatus, note: string | null): Promise<string>;
    recordExam(studentId: string, examName: string, examDate: string, subject: string, marks: string, remark: string | null): Promise<string>;
    recordFee(studentId: string, date: string, amount: string, paymentMode: string, note: string | null): Promise<string>;
    recordMonthlyTest(studentId: string, month: string, subject: string, marks: string, remark: string | null): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchStudents(nameFilter: string | null, mobileFilter: string | null): Promise<Array<Student>>;
    updateAttendance(id: string, status: AttendanceStatus, note: string | null): Promise<void>;
    updateStudent(id: string, name: string, fatherName: string, motherName: string, dateOfBirth: string, caste: string, mobileNumber: string, aadhaarNumber: string, penNumber: string, photo: ExternalBlob, address: string): Promise<void>;
}
import type { Attendance as _Attendance, AttendanceStatus as _AttendanceStatus, Exam as _Exam, ExternalBlob as _ExternalBlob, Fee as _Fee, MonthlyTest as _MonthlyTest, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: ExternalBlob, arg9: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getAttendanceRecordsByDateRange(arg0: string, arg1: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceRecordsByDateRange(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceRecordsByDateRange(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceRecordsByStudent(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceRecordsByStudent(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceRecordsByStudent(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamsByStudent(arg0: string): Promise<Array<Exam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamsByStudent(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamsByStudent(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeRecordsByStudent(arg0: string): Promise<Array<Fee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeRecordsByStudent(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeRecordsByStudent(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyTestsByStudent(arg0: string): Promise<Array<MonthlyTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyTestsByStudent(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyTestsByStudent(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Student_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Student_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordAttendance(arg0: string, arg1: string, arg2: AttendanceStatus, arg3: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(arg0, arg1, to_candid_AttendanceStatus_n32(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(arg0, arg1, to_candid_AttendanceStatus_n32(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async recordExam(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordExam(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordExam(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async recordFee(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFee(arg0, arg1, arg2, arg3, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFee(arg0, arg1, arg2, arg3, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async recordMonthlyTest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMonthlyTest(arg0, arg1, arg2, arg3, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMonthlyTest(arg0, arg1, arg2, arg3, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchStudents(arg0: string | null, arg1: string | null): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAttendance(arg0: string, arg1: AttendanceStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceStatus_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceStatus_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: ExternalBlob, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
}
function from_candid_AttendanceStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Exam_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exam): Exam {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Fee_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fee): Fee {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MonthlyTest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonthlyTest): MonthlyTest {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Student_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Promise<Student> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AttendanceStatus;
    studentId: string;
    date: string;
    note: [] | [string];
    createdAt: bigint;
    updatedAt: bigint;
}): {
    id: string;
    status: AttendanceStatus;
    studentId: string;
    date: string;
    note?: string;
    createdAt: bigint;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n14(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    marks: string;
    remark: [] | [string];
    studentId: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
    examDate: string;
    examName: string;
}): {
    id: string;
    marks: string;
    remark?: string;
    studentId: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
    examDate: string;
    examName: string;
} {
    return {
        id: value.id,
        marks: value.marks,
        remark: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.remark)),
        studentId: value.studentId,
        subject: value.subject,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        examDate: value.examDate,
        examName: value.examName
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    studentId: string;
    date: string;
    note: [] | [string];
    createdAt: bigint;
    updatedAt: bigint;
    paymentMode: string;
    amount: string;
}): {
    id: string;
    studentId: string;
    date: string;
    note?: string;
    createdAt: bigint;
    updatedAt: bigint;
    paymentMode: string;
    amount: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        paymentMode: value.paymentMode,
        amount: value.amount
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    marks: string;
    remark: [] | [string];
    month: string;
    studentId: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
}): {
    id: string;
    marks: string;
    remark?: string;
    month: string;
    studentId: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        marks: value.marks,
        remark: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.remark)),
        month: value.month,
        studentId: value.studentId,
        subject: value.subject,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dateOfBirth: string;
    caste: string;
    name: string;
    createdAt: bigint;
    motherName: string;
    mobileNumber: string;
    updatedAt: bigint;
    penNumber: string;
    fatherName: string;
    address: string;
    aadhaarNumber: string;
    photo: _ExternalBlob;
}): Promise<{
    id: string;
    dateOfBirth: string;
    caste: string;
    name: string;
    createdAt: bigint;
    motherName: string;
    mobileNumber: string;
    updatedAt: bigint;
    penNumber: string;
    fatherName: string;
    address: string;
    aadhaarNumber: string;
    photo: ExternalBlob;
}> {
    return {
        id: value.id,
        dateOfBirth: value.dateOfBirth,
        caste: value.caste,
        name: value.name,
        createdAt: value.createdAt,
        motherName: value.motherName,
        mobileNumber: value.mobileNumber,
        updatedAt: value.updatedAt,
        penNumber: value.penNumber,
        fatherName: value.fatherName,
        address: value.address,
        aadhaarNumber: value.aadhaarNumber,
        photo: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.photo)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exam>): Array<Exam> {
    return value.map((x)=>from_candid_Exam_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fee>): Array<Fee> {
    return value.map((x)=>from_candid_Fee_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MonthlyTest>): Array<MonthlyTest> {
    return value.map((x)=>from_candid_MonthlyTest_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Promise<Array<Student>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Student_n29(_uploadFile, _downloadFile, x)));
}
function to_candid_AttendanceStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
