/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : AttendanceStatus,
  'studentId' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Exam = IDL.Record({
  'id' : IDL.Text,
  'marks' : IDL.Text,
  'remark' : IDL.Opt(IDL.Text),
  'studentId' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'examDate' : IDL.Text,
  'examName' : IDL.Text,
});
export const Fee = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'paymentMode' : IDL.Text,
  'amount' : IDL.Text,
});
export const MonthlyTest = IDL.Record({
  'id' : IDL.Text,
  'marks' : IDL.Text,
  'remark' : IDL.Opt(IDL.Text),
  'month' : IDL.Text,
  'studentId' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'caste' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'motherName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'updatedAt' : IDL.Int,
  'penNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'photo' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getAttendanceRecordsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getAttendanceRecordsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
  'getFeeRecordsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Fee)], ['query']),
  'getMonthlyTestsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MonthlyTest)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, AttendanceStatus, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'recordExam' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'recordFee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'recordMonthlyTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudents' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'updateAttendance' : IDL.Func(
      [IDL.Text, AttendanceStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : AttendanceStatus,
    'studentId' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Exam = IDL.Record({
    'id' : IDL.Text,
    'marks' : IDL.Text,
    'remark' : IDL.Opt(IDL.Text),
    'studentId' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'examDate' : IDL.Text,
    'examName' : IDL.Text,
  });
  const Fee = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'paymentMode' : IDL.Text,
    'amount' : IDL.Text,
  });
  const MonthlyTest = IDL.Record({
    'id' : IDL.Text,
    'marks' : IDL.Text,
    'remark' : IDL.Opt(IDL.Text),
    'month' : IDL.Text,
    'studentId' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'caste' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'motherName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'updatedAt' : IDL.Int,
    'penNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'photo' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getAttendanceRecordsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceRecordsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
    'getFeeRecordsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Fee)], ['query']),
    'getMonthlyTestsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MonthlyTest)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, AttendanceStatus, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'recordExam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'recordFee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'recordMonthlyTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudents' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'updateAttendance' : IDL.Func(
        [IDL.Text, AttendanceStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };