/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : string,
  'status' : AttendanceStatus,
  'studentId' : string,
  'date' : string,
  'note' : [] | [string],
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface Exam {
  'id' : string,
  'marks' : string,
  'remark' : [] | [string],
  'studentId' : string,
  'subject' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'examDate' : string,
  'examName' : string,
}
export type ExternalBlob = Uint8Array;
export interface Fee {
  'id' : string,
  'studentId' : string,
  'date' : string,
  'note' : [] | [string],
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'paymentMode' : string,
  'amount' : string,
}
export interface MonthlyTest {
  'id' : string,
  'marks' : string,
  'remark' : [] | [string],
  'month' : string,
  'studentId' : string,
  'subject' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface Student {
  'id' : string,
  'dateOfBirth' : string,
  'caste' : string,
  'name' : string,
  'createdAt' : bigint,
  'motherName' : string,
  'mobileNumber' : string,
  'updatedAt' : bigint,
  'penNumber' : string,
  'fatherName' : string,
  'address' : string,
  'aadhaarNumber' : string,
  'photo' : ExternalBlob,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStudent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      string,
    ],
    string
  >,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getAttendanceRecordsByDateRange' : ActorMethod<
    [string, string],
    Array<Attendance>
  >,
  'getAttendanceRecordsByStudent' : ActorMethod<[string], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamsByStudent' : ActorMethod<[string], Array<Exam>>,
  'getFeeRecordsByStudent' : ActorMethod<[string], Array<Fee>>,
  'getMonthlyTestsByStudent' : ActorMethod<[string], Array<MonthlyTest>>,
  'getStudent' : ActorMethod<[string], Student>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAttendance' : ActorMethod<
    [string, string, AttendanceStatus, [] | [string]],
    string
  >,
  'recordExam' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    string
  >,
  'recordFee' : ActorMethod<
    [string, string, string, string, [] | [string]],
    string
  >,
  'recordMonthlyTest' : ActorMethod<
    [string, string, string, string, [] | [string]],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudents' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<Student>
  >,
  'updateAttendance' : ActorMethod<
    [string, AttendanceStatus, [] | [string]],
    undefined
  >,
  'updateStudent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];